### ISSUE TITLE
Настройка watchdog

### ISSUE THREAD

**Issue by SanSanichSan** [inspark/vmon#5]
**Environment:** Контроллер
**Steps to reproduce:** загрузка КОС по TFTP
**Expected Result**: загрузка КОС
**Actual Result:** не успевает загрузиться КОС, контроллер уходит по watchdog в перезагрузку.
Visual Proof (logs, screenshots, videos): -
[kos.boot.log](https://github.com/inspark/vmon/files/4076388/kos.boot.log)

**Comment by grekhss** [comment]
Для ускорения загрузки и преодоления данной проблемы предлагается следующее:

1. сохранить образ KOS на разделе внутренней ПЗУ (например, /opt/kos-image.stripped.bin)
2. в переменную bootcmd загрузчика сохранить команду запуска образа с раздела (например: setenv bootcmd "load mmc 0:2 0x40008000 /opt/kos-image.stripped.bin; go 0x400099A0")
3. сохранить переменные загрузчика командой saveenv

Тогда после каждойй перезагрузки будет сразу грузиться KOS с внутренней ПЗУ - это быстрее и не требует каждый раз вводить команды установки сетевого адреса и т.п.

**Comment by SanSanichSan** [comment]
делал так:
setenv autoload no
setenv bootcm "load mmc 0:2 0x40008000 /opt/kos-image.stripped.bin;" 
go 0x400099A0
[kos.boot.log](https://github.com/inspark/vmon/files/4076649/kos.boot.log)

**Comment by grekhss** [comment]
Так. Нужно проверить, что точка входа в образ соответствует адресу 0х400099А0.
Что показывает "readelf -h kos-image.stripped" ?
Ключевая строка:   `Entry point address:               0x********`

**Comment by SanSanichSan** [comment]
нет такой команды.
TFTP работает:
setenv ipaddr 10.4.2.231 
setenv serverip 10.4.2.230
tftp 0x40008000 10.4.2.230:kos-image.stripped.bin; go 0x400099a0

**Comment by grekhss** [comment]
> нет такой команды.

Это линуксовая команда, забыл написать, что её нужно выполнить на сборочном компьютере. Там где был создан загрузочный образ KOS.

> TFTP работает

Я правильно понимаю, что помощь по данному запросу не требуется?

**Comment by SanSanichSan** [comment]
С соседнего тома кос не нрузится.

**Comment by SanSanichSan** [comment]
У вас же много стендов.. почему мы пытаемся это делать через меня и теряем столько времени?:) темболее у вас все есть для того что б все это взлетело)

**Comment by grekhss** [comment]
> почему мы пытаемся это делать через меня и теряем столько времени?:)

В рамках прохождения процедуры релиза мы проводили комплексное тестирование всего проекта, которое включало в себя не только unit-тесты, но и проверку на отказоустойчивость (длительная работа под нагрузкой). Таким образом, есть все основания полагать, что система (аппаратная + программная часть) является работоспособной. Но несмотря на это с Вашей стороны наблюдаются сложности в запуске. Поэтому для решения возникшей проблемы необходимо в первую очередь выяснить детально в чём отличие наших тестов от Ваших запусков: версия кода, настройки окружения, особенности аппаратной части.

**Comment by SanSanichSan** [comment]
> Таким образом, есть все основания полагать, что система (аппаратная + программная часть) является работоспособной.

Тогда может вы все покажете, как это работает с облаком в автоматическом режиме, т.е. прошили контроллер и он проинициализировался и заработал в облаке, а потом по инструкции мы сделаем сборку? Уверен, так будет и проще и быстрее.

**Comment by grekhss** [comment]
> С соседнего тома кос не нрузится.

Логи можете показать?

**Comment by SanSanichSan** [comment]
> делал так:
> setenv autoload no
> setenv bootcm "load mmc 0:2 0x40008000 /opt/kos-image.stripped.bin;"
> go 0x400099A0
> [kos.boot.log](https://github.com/inspark/vmon/files/4076649/kos.boot.log)

выше

**Comment by grekhss** [comment]
Попробуйте выполнить из загрузчика вот эти две команды:
load mmc 0:2 0x40008000 /opt/kos-image.stripped.bin
go 0x400099A0

**Comment by SanSanichSan** [comment]
[kos.boot.log](https://github.com/inspark/vmon/files/4095972/kos.boot.log)

**Comment by grekhss** [comment]
> [kos.boot.log](https://github.com/inspark/vmon/files/4095972/kos.boot.log)

Грузится. Лог неполный в том смысле, что обрывается на обращении к ntp-серверу.

Что касается ранее опробованных команд:

> setenv autoload no
Эта команда в данной ситуации не нужна: переменная autoload влияет только на загрузку по сети.

> setenv bootcm "load mmc 0:2 0x40008000 /opt/kos-image.stripped.bin;"
Здесь выставляется неверная переменная bootcm (должна быть bootcmd) в значение "load mmc ...". Если выставить переменную bootcmd, то при перезагрузке устройства загрузчик u-boot попытается выполнить команду, сохранённую в этой переменной.

> go 0x400099A0
Здесь производится попытка выполнить команды, расположенные по адресу 0x400099A0. В данной ситуации это не будет иметь эффекта, потому что в память ничего не было загружено.

Если нужно, чтобы после перезагрузки устройства автоматически происходила загрузка образа с ПЗУ, то нужно выполнить следующие команды (**### имейте в виду, что предыдущее значение переменной bootcmd будет потеряно!**):

setenv bootcmd "load mmc 0:2 0x40008000 /opt/kos-image.stripped.bin; go 0x400099A0"
saveenv
reset

**Comment by grekhss** [comment]
> 100 попыток, потом
> VMON START MANAGER ERROR: NTP CAN NOT SET SYSTEM TIME, VMON STOPED !

Так. Это уже другая проблема. Закрываю этот вопрос. Перемещаемся обратно в синхронизацию времени.
